Feat/homepage event block
CSIS-iLab/energy-jti pull request #115
Opened 2020-12-01 20:43 UTC by smaraghi

2020-12-02 15:00 UTC, jnschrag requested changes
Thanks for looking at this! In general the styles are all great. I left a few comments, but there's a bigger concern here that I think got lost or miscommunicated in the shuffle of everything else going on.

The idea is that this block is optionally included on the home page if they have a future event they want to promote. So just like the featured analysis are set using an ACF, so is the featured event. There's a field for it on the "Home" page in the dashboard. If no featured post is selected, nothing is shown (ie. no message about upcoming events being posted here). The field has already been created, so you'll need to swap out the query stuff with that.

One other note, and I think it  might be worth asking Tucker what she thinks - the mockups indicate that the location should also be included here. However, most of the events they have show the full address, not something short like "Online" or "CSIS". I would ask Tucker if she thinks its still worth including in that case, or if it should be adjusted so they're vertically stacked instead of side by side.

2020-12-02 16:19 UTC, smaraghi commented on wp-content/themes/csisjti/assets/_scss/pages/home.scss
> +    display: flex;
To be honest, I was walking into a lot of code from a week ago and trying to make sense of it.

2020-12-02 16:24 UTC, smaraghi commented on wp-content/themes/csisjti/assets/_scss/pages/home.scss
> +        'heading date name'
So I can add align-self: center later on so that way heading and name are centered to the date object.

2020-12-02 16:34 UTC, smaraghi commented on wp-content/themes/csisjti/assets/_scss/pages/home.scss
> +    display: flex;
Better to start over with a clear head. Thanks for catching this.

2020-12-02 19:32 UTC, smaraghi commented
Spoke with Tucker. She believes the full address on the homepage would be too much to show and is not necessary. She stated adding a string that is 'In Person' or 'Online' and then filtering out the 'In-Person' string on the actual events page would be her recommendation but is not married to it. I do not think implementing this is necessary when most of their events are in-person, and at this point there are more important items to take care of. But I wanted your opinion as well.

2020-12-03 15:45 UTC, jnschrag approved these changes
This looks good to me.

I think it's fine to leave off the location - if the program asks about it, we can add in a separate field for the in person/online thing, but I agree with you that it doesn't really seem necessary here.

One note when you push this - can you update the "Featured Event" field to allow null values? I realized while testing it on my local that the field couldn't be empty. You can edit it in ACF -> Home.

2020-12-03 15:45 UTC, merged